'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    overview: 'Overview',
    myBooks: 'My Books',
    communities: 'Communities',
    settings: 'Settings',
    createNewBook: 'Create New Book',
    signOut: 'Sign Out',
    bookVerse: 'BookVerse',
    browse: 'Browse',
    // Settings Page
    profileSettings: 'Profile Settings',
    visualIdentity: 'Visual Identity',
    profileAvatar: 'Profile Avatar',
    profileBanner: 'Profile Banner',
    languagePreferences: 'Language & Preferences',
    interfaceLanguage: 'Interface Language',
    languageHelp: 'Changes the language of the sidebar and menus.',
    personalInfo: 'Personal Info',
    username: 'Username',
    usernameHelp: 'Username cannot be changed',
    displayName: 'Display Name',
    bio: 'Bio',
    bioPlaceholder: 'Tell your story...',
    socialConnections: 'Social Connections',
    aiConfiguration: 'AI Configuration',
    geminiApiKey: 'Gemini API Key',
    apiKeyHelp: 'Your key is stored securely and used only for your requests.',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    livePreview: 'Live Preview',
    yourName: 'Your Name',
    bioPreview: 'Your biography will appear here...',
    // Create Book
    bookEditor: 'Book Editor',
    editingMode: 'Editing Mode',
    draftMode: 'Draft Mode',
    untitled: 'Untitled',
    chapter: 'Chapter',
    saveDraft: 'Save Draft',
    save: 'Save',
    publish: 'Publish',
    publishBook: 'Publish Book',
    aiAssistant: 'AI Assistant',
    apiKey: 'API Key',
    pasteApiKey: 'Paste your Gemini API Key...',
    generationMode: 'Generation Mode',
    completeBook: 'Complete Book',
    structureOnly: 'Structure Only',
    singlePage: 'Single Page',
    betaReader: 'Beta Reader',
    prompt: 'Prompt',
    describeScene: 'Describe the scene...',
    describeBook: 'Describe your book idea...',
    analysisResult: 'Analysis Result',
    analysisPlaceholder: 'Analysis results will appear here...',
    length: 'Length',
    pagesCount: 'Pages',
    short: 'Short',
    medium: 'Medium',
    long: 'Long',
    generate: 'Generate',
    generating: 'Thinking...',
    howToGetKey: 'How to get key?',
    tutorialTitle: 'Get your Gemini API Key',
    step1Title: 'Go to Google AI Studio',
    step1Desc: 'Visit the Google AI Studio to generate your free API key.',
    openStudio: 'Open Google AI Studio',
    step2Title: 'Create API Key',
    step2Desc: 'Click on "Create API key" and select a project (or create a new one).',
    step3Title: 'Copy & Paste',
    step3Desc: 'Copy the generated key starting with AIza... and paste it into the input field here.',
    gotIt: 'Got it',
    freeApiNote: '✨ The Gemini API is currently free to use for personal projects!',
    // Editor Sidebar
    pagesTab: 'Pages',
    settingsTab: 'Settings',
    teamTab: 'Team',
    aiTab: 'AI',
    charsTab: 'Chars',
    structure: 'Structure',
    pagesCountLabel: 'Pages',
    addNewPage: 'Add New Page',
    untitledPage: 'Untitled Page',
    pageIndex: 'Page',
    // Editor Settings
    coverImage: 'Cover Image',
    uploadCover: 'Upload Cover',
    // Overview Page
    welcomeBack: 'Welcome back, {name}!',
    premiumAuthorDashboard: 'Premium Author Dashboard',
    readyToCreate: 'Ready to create your next masterpiece? You have {books} books published and {communities} communities active.',
    writeNewBook: 'Write New Book',
    totalBooksPublished: 'Total Books Published',
    communitiesJoined: 'Communities Joined',
    active: 'Active',
    totalRevenue: 'Total Revenue',
    recentProjects: 'Recent Projects',
    viewAll: 'View All',
    noBooksCreated: 'No books created yet. Start your journey today!',
    published: 'PUBLISHED',
    draft: 'DRAFT',
    quickActions: 'Quick Actions',
    joinCommunity: 'Join Community',
    connectWithOthers: 'Connect with others',
    editProfile: 'Edit Profile',
    updateBio: 'Update your bio',
    wallet: 'Wallet',
    manageEarnings: 'Manage earnings',
    communityActivity: 'Community Activity',
    noRecentActivity: 'No recent activity',
    showLess: 'Show Less',
    showMore: 'Show More',
    publishedBook: 'published',
    reviewedBook: 'reviewed a book',
    likedBook: 'liked a book',
    followedUser: 'started following someone',
    proTip: 'Pro Tip',
    proTipContent: 'Engaging with your community increases book sales by up to 40%.',
    goToCommunities: 'Go to Communities',
    thisMonth: 'this month',
    // Wallet Page
    totalBalance: 'Total Balance',
    addFunds: 'Add Funds',
    withdraw: 'Withdraw',
    monthlyOverview: 'Monthly Overview',
    totalEarnings: 'Total Earnings',
    transactions: 'Transactions',
    allTransactions: 'All',
    sales: 'Sales',
    tips: 'Tips',
    noTransactions: 'No transactions found for this period.',
    soldTo: 'Sold to',
    from: 'From',
    receivedTip: 'Received Tip',
    walletFeatureComingSoon: 'feature coming soon!',
    itemStore: 'Item Store',
    // Profile Page
    joined: 'Joined',
    booksCount: 'Books',
    communitiesCount: 'Communities',
    trophiesCount: 'Trophies',
    followersCount: 'Followers',
    noBooksTitle: 'No books published yet',
    noBooksDesc: 'This author hasn\'t published any books yet.',
    noAchievementsTitle: 'No achievements yet',
    noAchievementsDesc: 'This author hasn\'t unlocked any achievements yet.',
    follow: 'Follow',
    unfollow: 'Unfollow',
    message: 'Message',
    achievements: 'Achievements',
    activity: 'Activity',
    // Settings Page (Notifications)
    notificationSettings: 'Notification Settings',
    newFollowers: 'New Followers',
    newFollowersDesc: 'Notify me when someone follows me',
    bookComments: 'Book Comments',
    bookCommentsDesc: 'Notify me when someone comments on my book',
    systemUpdates: 'System Updates',
    systemUpdatesDesc: 'Notify me about platform updates and features',
    emailDigest: 'Email Digest',
    emailDigestDesc: 'Receive a weekly summary of activity',
    security: 'Security',
    // Subscription Page
    upgradeToPremium: 'Upgrade to Premium',
    upgradeTitle: 'Unlock Your Full Potential',
    upgradeSubtitle: 'Get unlimited access to premium books, exclusive features, and support the platform.',
    monthly: 'Monthly',
    yearly: 'Yearly',
    month: 'month',
    year: 'year',
    freePlan: 'Free',
    premiumPlan: 'Premium',
    freeDescription: 'Perfect for getting started',
    premiumDescription: 'For serious readers & writers',
    freeFeature1: 'Access to free books',
    freeFeature2: 'Create up to 3 books',
    freeFeature3: 'Basic community features',
    freeFeature4: 'Standard support',
    premiumFeature1: 'Unlimited access to ALL books',
    premiumFeature2: 'Unlimited book creation',
    premiumFeature3: 'Advanced AI writing assistant',
    premiumFeature4: 'Priority support 24/7',
    premiumFeature5: 'Exclusive community badges',
    premiumFeature6: 'Early access to new features',
    premiumFeature7: 'Custom profile frames',
    premiumFeature8: 'No ads ever',
    currentPlan: 'Current Plan',
    mostPopular: 'MOST POPULAR',
    savingsText: 'You save $19.89/year',
    subscribeNow: 'Subscribe Now',
    cancelSubscription: 'Cancel Subscription',
    cancelSubscriptionConfirm: 'Are you sure you want to cancel? You will lose access immediately.',
    securePayment: '🔒 Secure payment • Cancel anytime',
    securePaymentTitle: 'Secure Payment',
    securePaymentDesc: 'Your payment information is encrypted and secure.',
    instantAccessTitle: 'Instant Access',
    instantAccessDesc: 'Start reading premium content immediately after subscribing.',
    supportCreatorsTitle: 'Support Creators',
    supportCreatorsDesc: 'Your subscription directly supports the authors you love.',
    moneyBackGuarantee: '30-day money-back guarantee',
    description: 'Description',
    descriptionPlaceholder: 'Write a catchy blurb...',
    genres: 'Genres',
    addGenre: 'Add a Genre...',
    premiumContent: 'Premium Content',
    monetizeBook: 'Monetize your book',
    priceLabel: 'Price ($)',
    allowPdfDownload: 'Allow PDF Download',
    allowPdfDownloadDesc: 'Let readers download your book',
    ambience: 'Ambience',
    ambienceNone: 'None',
    ambienceRain: 'Rainy Day',
    ambienceFireplace: 'Cozy Fireplace',
    ambienceForest: 'Forest Sounds',
    ambienceCafe: 'Coffee Shop',
    ambienceSpace: 'Deep Space',
    ambienceOcean: 'Ocean Waves',
    // Editor Team
    inviteTeam: 'Invite Team',
    teamUsernamePlaceholder: 'Username',
    saveBookFirst: 'Save the book first to add collaborators.',
    members: 'Members',
    activeMembers: 'Active',
    noCollaborators: 'No collaborators yet',
    // Editor Main
    autoSaving: 'Auto-saving',
    charsCount: 'chars',
    pageOf: 'Page',
    of: 'of',
    toggleFocusMode: 'Toggle Focus Mode',
    preview: 'Preview',
    edit: 'Edit',
    untitledBook: 'Untitled Book',
    currentChapter: 'Current Chapter',
    nothingWritten: 'Nothing written yet...',
    editorPlaceholder: 'Once upon a time...',
    // Rich Editor
    bold: 'Bold',
    italic: 'Italic',
    strikethrough: 'Strikethrough',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    bulletList: 'Bullet List',
    orderedList: 'Ordered List',
    quote: 'Quote',
    startWriting: 'Start writing...',
    // My Books Header
    myLibrary: 'My Library',
    manageMasterpieces: 'Manage your masterpieces. You have {{count}} projects in total.',
    projectsInTotal: 'projects in total',
    total: 'Total',
    // BookList
    searchPlaceholder: 'Search your library...',
    allStatus: 'All Status',
    publishedStatus: 'Published',
    draftStatus: 'Drafts',
    noBooksFound: 'No books found',
    noBooksFoundDesc: "We couldn't find any books matching your search. Try adjusting your filters or create a new one.",
    clearFilters: 'Clear filters',
    noCover: 'No Cover',
    editBook: 'Edit Book',
    viewAnalytics: 'View Analytics',
    startReadingParty: 'Start a Reading Party for this book?',
    readingParty: 'Reading Party',
    deleteBookTitle: 'Delete Book',
    deleteConfirmation: 'Are you sure you want to delete this book? This action cannot be undone.',
    failedToDelete: 'Failed to delete book',
    failedToCreateRoom: 'Failed to create room',
    bookAnalytics: 'Book Analytics',
    // Analytics Dashboard
    failedToLoadAnalytics: 'Failed to load analytics',
    totalReaders: 'Total Readers',
    completionRate: 'Completion Rate',
    avgProgress: 'Avg. Progress',
    readerRetention: 'Reader Retention (Funnel)',
    readersReachingEachPage: 'Readers reaching each page',
    pageLabel: 'Page {{page}}',
    readersCount: '{{count}} readers',
    // Communities
    connectCollaborate: 'Connect & Collaborate',
    discoverTribe: 'Discover Your Tribe',
    communitiesDesc: 'Join discussions, share your stories, and connect with fellow readers and authors in specialized communities designed for you.',
    createCommunity: 'Create Community',
    searchCommunities: 'Search communities...',
    bookVerseHub: 'BookVerse Hub',
    officialCommunity: 'Official Community',
    activeNow: 'Active Now',
    join: 'Join',
    noCommunitiesFound: 'No communities found',
    noCommunitiesDesc: 'It looks like there are no communities yet. Why not be the pioneer and create the first one?',
    createFirstCommunity: 'Create First Community',
    allCommunities: 'All Communities',
    popular: 'Popular',
    newest: 'Newest',
    myCommunities: 'My Communities',
    fiction: 'Fiction',
    nonFiction: 'Non-Fiction',
    romance: 'Romance',
    sciFi: 'Sci-Fi',
    defaultCommunityDesc: 'Join this community to connect with others and share your passion.',
    member: 'Member',
    createCommunityTitle: 'Create a Community',
    createCommunitySubtitle: 'Start a space for readers to discuss your favorite topics.',
    communityName: 'Community Name',
    communityNamePlaceholder: 'e.g., Fantasy Lovers',
    communityDescription: 'Description',
    communityDescriptionPlaceholder: 'What is this community about?',
    privacy: 'Privacy',
    privacyOpen: 'Open (Anyone can join)',
    privacyClosed: 'Closed (Requires approval)',
    private: 'Private',
    community: 'Community',
    noDescription: 'No description provided.',
    requestPending: 'Request Pending',
    requestToJoin: 'Request to Join',
    joinCommunityButton: 'Join Community',
    communityFeed: 'Community Feed',
    latest: 'Latest',
    top: 'Top',
    quietInHere: 'Quiet in here...',
    beTheFirst: 'Be the first to spark a conversation in this community!',
    aboutCommunity: 'About Community',
    aboutCommunityDesc: 'Welcome to our community! Connect, share, and grow with us.',
    membersCount: 'Members',
    postsCount: 'Posts',
    created: 'Created',
    createdBy: 'Created By',
    failedToPost: 'Failed to post',
    shareSomething: 'Share something with the community...',
    postButton: 'Post',
    like: 'Like',
    likes: 'Likes',
    comments: 'Comments',
    writeComment: 'Write a comment...',
    reply: 'Reply',
    loadMore: 'Load more comments',
    deleteCommunityConfirm: 'Are you sure you want to delete this community? This action cannot be undone.',
    failedToDeleteCommunity: 'Failed to delete community',
    deleteCommunityButton: 'Delete Community',
  },
  pt: {
    overview: 'Visão Geral',
    myBooks: 'Minha Biblioteca',
    communities: 'Comunidades',
    settings: 'Configurações',
    createNewBook: 'Criar Novo Livro',
    signOut: 'Sair',
    bookVerse: 'BookVerse',
    browse: 'Explorar',
    // Settings Page
    profileSettings: 'Configurações do Perfil',
    visualIdentity: 'Identidade Visual',
    profileAvatar: 'Foto de Perfil',
    profileBanner: 'Banner do Perfil',
    languagePreferences: 'Idioma e Preferências',
    interfaceLanguage: 'Idioma da Interface',
    languageHelp: 'Altera o idioma da barra lateral e menus.',
    personalInfo: 'Informações Pessoais',
    username: 'Nome de Usuário',
    usernameHelp: 'O nome de usuário não pode ser alterado',
    displayName: 'Nome de Exibição',
    bio: 'Sobre Mim',
    bioPlaceholder: 'Conte sua história...',
    socialConnections: 'Redes Sociais',
    aiConfiguration: 'Configuração de IA',
    geminiApiKey: 'Chave da API Gemini',
    apiKeyHelp: 'Sua chave é armazenada com segurança e usada apenas para suas solicitações.',
    saveChanges: 'Salvar Alterações',
    saving: 'Salvando...',
    livePreview: 'Pré-visualização',
    yourName: 'Seu Nome',
    bioPreview: 'Sua biografia aparecerá aqui...',
    // Create Book
    bookEditor: 'Editor de Livros',
    editingMode: 'Modo de Edição',
    draftMode: 'Modo Rascunho',
    untitled: 'Sem Título',
    chapter: 'Capítulo',
    saveDraft: 'Salvar Rascunho',
    save: 'Salvar',
    publish: 'Publicar',
    publishBook: 'Publicar Livro',
    aiAssistant: 'Assistente de IA',
    apiKey: 'Chave da API',
    pasteApiKey: 'Cole sua chave da API Gemini...',
    generationMode: 'Modo de Geração',
    completeBook: 'Livro Completo',
    structureOnly: 'Apenas Estrutura',
    singlePage: 'Página Única',
    betaReader: 'Leitor Beta',
    prompt: 'Prompt',
    describeScene: 'Descreva a cena...',
    describeBook: 'Descreva sua ideia de livro...',
    analysisResult: 'Resultado da Análise',
    analysisPlaceholder: 'Os resultados da análise aparecerão aqui...',
    length: 'Comprimento',
    pagesCount: 'Páginas',
    short: 'Curto',
    medium: 'Médio',
    long: 'Longo',
    generate: 'Gerar',
    generating: 'Pensando...',
    howToGetKey: 'Como obter a chave?',
    tutorialTitle: 'Obtenha sua chave da API Gemini',
    step1Title: 'Vá para o Google AI Studio',
    step1Desc: 'Visite o Google AI Studio para gerar sua chave de API gratuita.',
    openStudio: 'Abrir Google AI Studio',
    step2Title: 'Criar Chave de API',
    step2Desc: 'Clique em "Create API key" e selecione um projeto (ou crie um novo).',
    step3Title: 'Copiar e Colar',
    step3Desc: 'Copie a chave gerada começando com AIza... e cole-a no campo de entrada aqui.',
    gotIt: 'Entendi',
    freeApiNote: '✨ A API Gemini é atualmente gratuita para projetos pessoais!',
    // Editor Sidebar
    pagesTab: 'Páginas',
    settingsTab: 'Configurações',
    teamTab: 'Equipe',
    aiTab: 'IA',
    charsTab: 'Personagens',
    // Overview Page
    welcomeBack: 'Bem-vindo de volta, {name}!',
    premiumAuthorDashboard: 'Painel Premium de Autor',
    readyToCreate: 'Pronto para criar sua próxima obra-prima? Você tem {books} livros publicados e {communities} comunidades ativas.',
    writeNewBook: 'Escrever Novo Livro',
    totalBooksPublished: 'Total de Livros Publicados',
    communitiesJoined: 'Comunidades Participando',
    active: 'Ativo',
    totalRevenue: 'Receita Total',
    recentProjects: 'Projetos Recentes',
    viewAll: 'Ver Todos',
    noBooksCreated: 'Nenhum livro criado ainda. Comece sua jornada hoje!',
    published: 'PUBLICADO',
    draft: 'RASCUNHO',
    quickActions: 'Ações Rápidas',
    joinCommunity: 'Entrar em Comunidade',
    connectWithOthers: 'Conecte-se com outros',
    editProfile: 'Editar Perfil',
    updateBio: 'Atualize sua bio',
    wallet: 'Carteira',
    manageEarnings: 'Gerenciar ganhos',
    proTip: 'Dica Pro',
    proTipContent: 'Interagir com sua comunidade aumenta as vendas de livros em até 40%.',
    goToCommunities: 'Ir para Comunidades',
    thisMonth: 'este mês',
    // Wallet Page
    totalBalance: 'Saldo Total',
    addFunds: 'Adicionar Fundos',
    withdraw: 'Sacar',
    monthlyOverview: 'Resumo Mensal',
    totalEarnings: 'Ganhos Totais',
    transactions: 'Transações',
    allTransactions: 'Todas',
    sales: 'Vendas',
    tips: 'Gorjetas',
    noTransactions: 'Nenhuma transação encontrada neste período.',
    soldTo: 'Vendido para',
    from: 'De',
    receivedTip: 'Gorjeta Recebida',
    walletFeatureComingSoon: 'recurso em breve!',
    noDescription: 'Sem descrição',
    itemStore: 'Loja de Itens',
    // Profile Page
    joined: 'Entrou em',
    booksCount: 'Livros',
    communitiesCount: 'Comunidades',
    trophiesCount: 'Troféus',
    followersCount: 'Seguidores',
    noBooksTitle: 'Nenhum livro publicado',
    noBooksDesc: 'Este autor ainda não publicou nenhum livro.',
    noAchievementsTitle: 'Nenhuma conquista',
    noAchievementsDesc: 'Este autor ainda não desbloqueou nenhuma conquista.',
    follow: 'Seguir',
    unfollow: 'Deixar de Seguir',
    message: 'Mensagem',
    achievements: 'Conquistas',
    activity: 'Atividade',
    // Settings Page (Notifications)
    notificationSettings: 'Config. de Notificações',
    newFollowers: 'Novos Seguidores',
    newFollowersDesc: 'Notificar quando alguém me seguir',
    bookComments: 'Comentários em Livros',
    bookCommentsDesc: 'Notificar quando comentarem no meu livro',
    systemUpdates: 'Atualizações do Sistema',
    systemUpdatesDesc: 'Novidades sobre a plataforma e recursos',
    emailDigest: 'Resumo por Email',
    emailDigestDesc: 'Receber um resumo semanal de atividades',
    security: 'Segurança',
    // Subscription Page
    upgradeToPremium: 'Atualizar para Premium',
    upgradeTitle: 'Desbloqueie Todo Seu Potencial',
    upgradeSubtitle: 'Tenha acesso ilimitado a livros premium, recursos exclusivos e apoie a plataforma.',
    monthly: 'Mensal',
    yearly: 'Anual',
    month: 'mês',
    year: 'ano',
    freePlan: 'Grátis',
    premiumPlan: 'Premium',
    freeDescription: 'Perfeito para começar',
    premiumDescription: 'Para leitores e escritores dedicados',
    freeFeature1: 'Acesso a livros gratuitos',
    freeFeature2: 'Criar até 3 livros',
    freeFeature3: 'Recursos básicos de comunidade',
    freeFeature4: 'Suporte padrão',
    premiumFeature1: 'Acesso ilimitado a TODOS os livros',
    premiumFeature2: 'Criação ilimitada de livros',
    premiumFeature3: 'Assistente de escrita com IA avançada',
    premiumFeature4: 'Suporte prioritário 24/7',
    premiumFeature5: 'Emblemas exclusivos de comunidade',
    premiumFeature6: 'Acesso antecipado a novos recursos',
    premiumFeature7: 'Molduras de perfil personalizadas',
    premiumFeature8: 'Sem anúncios nunca',
    currentPlan: 'Plano Atual',
    mostPopular: 'MAIS POPULAR',
    savingsText: 'Você economiza R$19,89/ano',
    subscribeNow: 'Assinar Agora',
    cancelSubscription: 'Cancelar Assinatura',
    cancelSubscriptionConfirm: 'Tem certeza que deseja cancelar? Você perderá o acesso imediatamente.',
    securePayment: '🔒 Pagamento seguro • Cancele quando quiser',
    securePaymentTitle: 'Pagamento Seguro',
    securePaymentDesc: 'Suas informações de pagamento são criptografadas e seguras.',
    instantAccessTitle: 'Acesso Instantâneo',
    instantAccessDesc: 'Comece a ler conteúdo premium imediatamente após assinar.',
    supportCreatorsTitle: 'Apoie Criadores',
    supportCreatorsDesc: 'Sua assinatura apoia diretamente os autores que você ama.',
    moneyBackGuarantee: 'Garantia de 30 dias de devolução',
    structure: 'Estrutura',
    monetizeBook: 'Monetize seu livro',
    priceLabel: 'Preço ($)',
    allowPdfDownload: 'Permitir Download de PDF',
    allowPdfDownloadDesc: 'Permitir que leitores baixem seu livro',
    ambience: 'Ambiente',
    ambienceNone: 'Nenhum',
    ambienceRain: 'Dia Chuvoso',
    ambienceFireplace: 'Lareira Aconchegante',
    ambienceForest: 'Sons da Floresta',
    ambienceCafe: 'Cafeteria',
    ambienceSpace: 'Espaço Profundo',
    ambienceOcean: 'Ondas do Oceano',
    // Editor Team
    inviteTeam: 'Convidar Equipe',
    teamUsernamePlaceholder: 'Nome de usuário',
    saveBookFirst: 'Salve o livro primeiro para adicionar colaboradores.',
    members: 'Membros',
    activeMembers: 'Ativos',
    noCollaborators: 'Sem colaboradores ainda',
    // Editor Main
    autoSaving: 'Salvando auto.',
    charsCount: 'caracteres',
    pageOf: 'Página',
    of: 'de',
    toggleFocusMode: 'Alternar Modo Foco',
    preview: 'Visualizar',
    edit: 'Editar',
    untitledBook: 'Livro Sem Título',
    currentChapter: 'Capítulo Atual',
    nothingWritten: 'Nada escrito ainda...',
    editorPlaceholder: 'Era uma vez...',
    // Rich Editor
    bold: 'Negrito',
    italic: 'Itálico',
    strikethrough: 'Tachado',
    heading1: 'Título 1',
    heading2: 'Título 2',
    bulletList: 'Lista com Marcadores',
    orderedList: 'Lista Numerada',
    quote: 'Citação',
    startWriting: 'Comece a escrever...',
    // Image Upload
    uploadImage: 'Enviar Imagem',
    uploading: 'Enviando...',
    imageUploadError: 'Erro ao enviar imagem',
    imageUploadSuccess: 'Imagem enviada com sucesso',
    selectImage: 'Selecionar Imagem',
    changeImage: 'Alterar Imagem',
    removeImage: 'Remover Imagem',
    fileTooLarge: 'O arquivo é muito grande. O tamanho máximo é 25MB.',
    largeImageWarning: 'Esta imagem tem {{size}}MB.\n\nImagens grandes podem demorar para carregar (30-60 segundos).\n\nConsidere comprimi-la primeiro para melhor desempenho.\n\nContinuar mesmo assim?',
    compressionError: 'Erro de compressão:',
    failedToProcessImage: 'Falha ao processar imagem',
    processingImage: 'Processando...',
    clickToUploadImage: 'Clique para enviar imagem',
    maxFileSize: 'Máx 25MB',
    // Auth
    loginWelcomeBack: 'Bem-vindo de Volta',
    signInToContinue: 'Entre para continuar sua jornada',
    emailLabel: 'Email',
    passwordLabel: 'Senha',
    signInButton: 'Entrar',
    signingInButton: 'Entrando...',
    dontHaveAccount: 'Não tem uma conta?',
    signUpLink: 'Cadastre-se',
    backToHome: 'Voltar para Início',
    loginFailed: 'Falha no login',
    errorOccurred: 'Ocorreu um erro. Por favor, tente novamente.',
    createAccount: 'Criar Conta',
    joinCommunitySubtitle: 'Junte-se à comunidade BookVerse hoje',
    usernameLabel: 'Nome de Usuário',
    usernamePlaceholder: 'usuario_unico',
    usernamePatternError: 'O nome de usuário pode conter apenas letras, números, pontos e sublinhados',
    usernameHelper: 'Apenas letras, números, pontos e sublinhados permitidos.',
    signUpButton: 'Cadastrar',
    creatingAccountButton: 'Criando Conta...',
    alreadyHaveAccount: 'Já tem uma conta?',
    signInLink: 'Entrar',
    registrationFailed: 'Falha no cadastro',
    // My Books Header
    myLibrary: 'Minha Biblioteca',
    manageMasterpieces: 'Gerencie suas obras-primas. Você tem {{count}} projetos no total.',
    projectsInTotal: 'projetos no total',
    total: 'Total',
    // BookList
    searchPlaceholder: 'Pesquise sua biblioteca...',
    allStatus: 'Todos os Status',
    publishedStatus: 'Publicado',
    draftStatus: 'Rascunhos',
    noBooksFound: 'Nenhum livro encontrado',
    noBooksFoundDesc: 'Não encontramos nenhum livro correspondente à sua pesquisa. Tente ajustar seus filtros ou crie um novo.',
    clearFilters: 'Limpar filtros',
    noCover: 'Sem Capa',
    editBook: 'Editar Livro',
    viewAnalytics: 'Ver Análises',
    startReadingParty: 'Iniciar uma Festa de Leitura para este livro?',
    readingParty: 'Festa de Leitura',
    deleteBookTitle: 'Excluir Livro',
    deleteConfirmation: 'Tem certeza de que deseja excluir este livro? Esta ação não pode ser desfeita.',
    failedToDelete: 'Falha ao excluir livro',
    failedToCreateRoom: 'Falha ao criar sala',
    bookAnalytics: 'Análise do Livro',
    // Analytics Dashboard
    failedToLoadAnalytics: 'Falha ao carregar análises',
    totalReaders: 'Total de Leitores',
    completionRate: 'Taxa de Conclusão',
    avgProgress: 'Progresso Médio',
    readerRetention: 'Retenção de Leitores (Funil)',
    readersReachingEachPage: 'Leitores alcançando cada página',
    pageLabel: 'Página {{page}}',
    readersCount: '{{count}} leitores',
    // Communities
    connectCollaborate: 'Conectar & Colaborar',
    discoverTribe: 'Encontre sua Comunidade',
    communitiesDesc: 'Participe de discussões, compartilhe suas histórias e conecte-se com outros leitores e autores em comunidades especializadas.',
    createCommunity: 'Criar Comunidade',
    searchCommunities: 'Pesquisar comunidades...',
    bookVerseHub: 'BookVerse Hub',
    officialCommunity: 'Comunidade Oficial',
    activeNow: 'Ativo Agora',
    join: 'Entrar',
    noCommunitiesFound: 'Nenhuma comunidade encontrada',
    noCommunitiesDesc: 'Parece que ainda não há comunidades. Que tal ser o pioneiro e criar a primeira?',
    createFirstCommunity: 'Criar Primeira Comunidade',
    allCommunities: 'Todas as Comunidades',
    popular: 'Populares',
    newest: 'Mais Recentes',
    myCommunities: 'Minhas Comunidades',
    fiction: 'Ficção',
    nonFiction: 'Não-Ficção',
    romance: 'Romance',
    sciFi: 'Ficção Científica',
    defaultCommunityDesc: 'Junte-se a esta comunidade para se conectar com outros e compartilhar sua paixão.',
    member: 'Membro',
    createCommunityTitle: 'Criar uma Comunidade',
    createCommunitySubtitle: 'Inicie um espaço para leitores discutirem seus tópicos favoritos.',
    communityName: 'Nome da Comunidade',
    communityNamePlaceholder: 'ex: Amantes de Fantasia',
    communityDescription: 'Descrição',
    communityDescriptionPlaceholder: 'Sobre o que é esta comunidade?',
    privacy: 'Privacidade',
    privacyOpen: 'Aberta (Qualquer um pode entrar)',
    privacyClosed: 'Fechada (Requer aprovação)',
    private: 'Privada',
    community: 'Comunidade',
    requestPending: 'Solicitação Pendente',
    requestToJoin: 'Solicitar Entrada',
    joinCommunityButton: 'Entrar na Comunidade',
    communityFeed: 'Feed da Comunidade',
    latest: 'Recentes',
    top: 'Top',
    quietInHere: 'Silêncio por aqui...',
    beTheFirst: 'Seja o primeiro a iniciar uma conversa nesta comunidade!',
    aboutCommunity: 'Sobre a Comunidade',
    aboutCommunityDesc: 'Bem-vindo à nossa comunidade! Conecte-se, compartilhe e cresça conosco.',
    membersCount: 'Membros',
    postsCount: 'Postagens',
    created: 'Criado em',
    createdBy: 'Criado Por',
    failedToPost: 'Falha ao postar',
    shareSomething: 'Compartilhe algo com a comunidade...',
    postButton: 'Postar',
    like: 'Curtida',
    likes: 'Curtidas',
    comments: 'Comentários',
    writeComment: 'Escreva um comentário...',
    reply: 'Responder',
    loadMore: 'Carregar mais comentários',
    deleteCommunityConfirm: 'Tem certeza de que deseja excluir esta comunidade? Esta ação não pode ser desfeita.',
    failedToDeleteCommunity: 'Falha ao excluir comunidade',
    deleteCommunityButton: 'Excluir Comunidade',
    communityActivity: 'Atividade da Comunidade',
    noRecentActivity: 'Sem atividade recente',
    showLess: 'Mostrar Menos',
    showMore: 'Mostrar Mais',
    publishedBook: 'publicou',
    reviewedBook: 'avaliou um livro',
    likedBook: 'curtiu um livro',
    followedUser: 'começou a seguir alguém',
  },
  jp: {
    overview: '概要',
    myBooks: '私の本',
    communities: 'コミュニティ',
    settings: '設定',
    createNewBook: '新しい本を作成',
    signOut: 'サインアウト',
    bookVerse: 'ブックバース',
    browse: '閲覧',
    // Settings Page
    profileSettings: 'プロフィール設定',
    visualIdentity: 'ビジュアルアイデンティティ',
    profileAvatar: 'プロフィールアバター',
    profileBanner: 'プロフィールバナー',
    languagePreferences: '言語と設定',
    interfaceLanguage: 'インターフェース言語',
    languageHelp: 'サイドバーとメニューの言語を変更します。',
    personalInfo: '個人情報',
    username: 'ユーザー名',
    usernameHelp: 'ユーザー名は変更できません',
    displayName: '表示名',
    bio: '自己紹介',
    bioPlaceholder: 'あなたの物語を語ってください...',
    socialConnections: 'ソーシャル接続',
    aiConfiguration: 'AI設定',
    geminiApiKey: 'Gemini APIキー',
    apiKeyHelp: 'キーは安全に保存され、リクエストにのみ使用されます。',
    saveChanges: '変更を保存',
    saving: '保存中...',
    livePreview: 'ライブプレビュー',
    yourName: 'あなたの名前',
    bioPreview: 'あなたの自己紹介がここに表示されます...',
    // Create Book
    bookEditor: 'ブックエディター',
    editingMode: '編集モード',
    draftMode: '下書きモード',
    untitled: '無題',
    chapter: '章',
    saveDraft: '下書きを保存',
    save: '保存',
    publish: '公開',
    publishBook: '本を出版',
    aiAssistant: 'AIアシスタント',
    apiKey: 'APIキー',
    pasteApiKey: 'Gemini APIキーを貼り付けてください...',
    generationMode: '生成モード',
    completeBook: '本全体',
    structureOnly: '構成のみ',
    singlePage: '単一ページ',
    betaReader: 'ベータリーダー',
    prompt: 'プロンプト',
    describeScene: 'シーンを説明してください...',
    describeBook: '本のアイデアを説明してください...',
    analysisResult: '分析結果',
    analysisPlaceholder: '分析結果がここに表示されます...',
    length: '長さ',
    pagesCount: 'ページ数',
    short: '短い',
    medium: '中くらい',
    long: '長い',
    generate: '生成',
    generating: '考え中...',
    howToGetKey: 'キーの取得方法',
    tutorialTitle: 'Gemini APIキーを取得する',
    step1Title: 'Google AI Studioへ移動',
    step1Desc: 'Google AI Studioにアクセスして、無料のAPIキーを生成します。',
    openStudio: 'Google AI Studioを開く',
    step2Title: 'APIキーを作成',
    step2Desc: '「Create API key」をクリックし、プロジェクトを選択（または新規作成）します。',
    step3Title: 'コピー＆ペースト',
    step3Desc: 'AIza...で始まる生成されたキーをコピーして、ここの入力フィールドに貼り付けます。',
    gotIt: '了解',
    freeApiNote: '✨ Gemini APIは現在、個人プロジェクトで無料で使用できます！',
    // Editor Sidebar
    pagesTab: 'ページ',
    settingsTab: '設定',
    teamTab: 'チーム',
    aiTab: 'AI',
    charsTab: 'キャラ',
    structure: '構成',
    pagesCountLabel: 'ページ',
    addNewPage: '新しいページを追加',
    untitledPage: '無題のページ',
    pageIndex: 'ページ',
    // Editor Settings
    coverImage: '表紙画像',
    uploadCover: '表紙をアップロード',
    // Overview Page
    welcomeBack: 'お帰りなさい、{name}さん！',
    premiumAuthorDashboard: 'プレミアム著者ダッシュボード',
    readyToCreate: '次の傑作を作る準備はできましたか？ {books}冊の本が出版され、{communities}つのコミュニティがアクティブです。',
    writeNewBook: '新しい本を書く',
    totalBooksPublished: '出版された本の総数',
    communitiesJoined: '参加しているコミュニティ',
    active: 'アクティブ',
    totalRevenue: '総収益',
    recentProjects: '最近のプロジェクト',
    viewAll: 'すべて見る',
    noBooksCreated: 'まだ本が作成されていません。今日から旅を始めましょう！',
    published: '公開済み',
    draft: '下書き',
    quickActions: 'クイックアクション',
    joinCommunity: 'コミュニティに参加',
    connectWithOthers: '他の人とつながる',
    editProfile: 'プロフィールを編集',
    updateBio: '自己紹介を更新',
    wallet: 'ウォレット',
    manageEarnings: '収益を管理',
    communityActivity: 'コミュニティ活動',
    proTip: 'プロのヒント',
    proTipContent: 'コミュニティと交流することで、本の売り上げが最大40％増加します。',
    goToCommunities: 'コミュニティへ移動',
    thisMonth: '今月',
    // Wallet Page
    totalBalance: '総残高',
    addFunds: '資金を追加',
    withdraw: '引き出し',
    monthlyOverview: '月間概要',
    totalEarnings: '総収益',
    transactions: '取引',
    allTransactions: 'すべて',
    sales: '売上',
    tips: 'チップ',
    noTransactions: 'この期間の取引は見つかりませんでした。',
    soldTo: '販売先',
    from: '送信元',
    receivedTip: 'チップを受け取りました',
    walletFeatureComingSoon: '機能は近日公開予定！',
    itemStore: 'アイテムストア',
    // Profile Page
    joined: '登録日',
    booksCount: '本',
    communitiesCount: 'コミュニティ',
    trophiesCount: 'トロフィー',
    followersCount: 'フォロワー',
    noBooksTitle: '本はまだ公開されていません',
    noBooksDesc: 'この著者はまだ本を公開していません。',
    noAchievementsTitle: '実績なし',
    noAchievementsDesc: 'この著者はまだ実績を解除していません。',
    follow: 'フォロー',
    unfollow: 'フォロー解除',
    message: 'メッセージ',
    achievements: '実績',
    activity: 'アクティビティ',
    // Settings Page (Notifications)
    notificationSettings: '通知設定',
    newFollowers: '新しいフォロワー',
    newFollowersDesc: '誰かが私をフォローしたときに通知する',
    bookComments: '本へのコメント',
    bookCommentsDesc: '本にコメントがついたときに通知する',
    systemUpdates: 'システム更新',
    systemUpdatesDesc: 'プラットフォームの更新や機能について通知する',
    emailDigest: 'メールダイジェスト',
    emailDigestDesc: 'アクティビティの週次概要を受け取る',
    security: 'セキュリティ',
    // Subscription Page
    upgradeToPremium: 'プレミアムにアップグレード',
    upgradeTitle: '可能性を最大限に引き出す',
    upgradeSubtitle: 'プレミアム書籍への無制限アクセス、限定機能、プラットフォームのサポートを手に入れましょう。',
    monthly: '月額',
    yearly: '年額',
    month: '月',
    year: '年',
    freePlan: '無料',
    premiumPlan: 'プレミアム',
    freeDescription: '始めるのに最適',
    premiumDescription: '真剣な読者と作家向け',
    freeFeature1: '無料本へのアクセス',
    freeFeature2: '最大3冊まで作成可能',
    freeFeature3: '基本的なコミュニティ機能',
    freeFeature4: '標準サポート',
    premiumFeature1: 'すべての本に無制限アクセス',
    premiumFeature2: '無制限の本の作成',
    premiumFeature3: '高度なAIライティングアシスタント',
    premiumFeature4: '24時間365日優先サポート',
    premiumFeature5: '限定コミュニティバッジ',
    premiumFeature6: '新機能への早期アクセス',
    premiumFeature7: 'カスタムプロフィールフレーム',
    premiumFeature8: '広告なし',
    currentPlan: '現在のプラン',
    mostPopular: '最も人気',
    savingsText: '年間$19.89お得',
    subscribeNow: '今すぐ登録',
    cancelSubscription: '登録をキャンセル',
    cancelSubscriptionConfirm: 'キャンセルしてもよろしいですか？すぐにアクセスが失われます。',
    securePayment: '🔒 安全な支払い • いつでもキャンセル可能',
    securePaymentTitle: '安全な支払い',
    securePaymentDesc: 'お支払い情報は暗号化され、安全に保護されています。',
    instantAccessTitle: '即時アクセス',
    instantAccessDesc: '登録後すぐにプレミアムコンテンツを読み始められます。',
    supportCreatorsTitle: 'クリエイターを支援',
    supportCreatorsDesc: 'あなたの登録は、愛する著者を直接サポートします。',
    moneyBackGuarantee: '30日間の返金保証',
    description: '説明',
    descriptionPlaceholder: '魅力的な宣伝文句を書いてください...',
    genres: 'ジャンル',
    addGenre: 'ジャンルを追加...',
    premiumContent: 'プレミアムコンテンツ',
    monetizeBook: '本を収益化',
    priceLabel: '価格 ($)',
    allowPdfDownload: 'PDFダウンロードを許可',
    allowPdfDownloadDesc: '読者が本をダウンロードできるようにする',
    ambience: '環境音',
    ambienceNone: 'なし',
    ambienceRain: '雨の日',
    ambienceFireplace: '居心地の良い暖炉',
    ambienceForest: '森の音',
    ambienceCafe: 'コーヒーショップ',
    ambienceSpace: '深宇宙',
    ambienceOcean: '海の波',
    // Editor Team
    inviteTeam: 'チームを招待',
    teamUsernamePlaceholder: 'ユーザー名',
    saveBookFirst: 'コラボレーターを追加するには、まず本を保存してください。',
    members: 'メンバー',
    activeMembers: 'アクティブ',
    noCollaborators: 'コラボレーターはまだいません',
    // Editor Main
    autoSaving: '自動保存中',
    charsCount: '文字',
    pageOf: 'ページ',
    of: '/',
    toggleFocusMode: 'フォーカスモード切替',
    preview: 'プレビュー',
    edit: '編集',
    untitledBook: '無題の本',
    currentChapter: '現在の章',
    nothingWritten: 'まだ何も書かれていません...',
    editorPlaceholder: '昔々あるところに...',
    // Rich Editor
    bold: '太字',
    italic: '斜体',
    strikethrough: '取り消し線',
    heading1: '見出し 1',
    heading2: '見出し 2',
    bulletList: '箇条書き',
    orderedList: '番号付きリスト',
    quote: '引用',
    startWriting: '書き始める...',
    // Image Upload
    uploadImage: '画像をアップロード',
    uploading: 'アップロード中...',
    imageUploadError: '画像のアップロードエラー',
    imageUploadSuccess: '画像が正常にアップロードされました',
    selectImage: '画像を選択',
    changeImage: '画像を変更',
    removeImage: '画像を削除',
    fileTooLarge: 'ファイルが大きすぎます。最大サイズは25MBです。',
    largeImageWarning: 'この画像は{{size}}MBです。\n\n大きな画像はアップロードに時間がかかる場合があります（30〜60秒）。\n\nパフォーマンス向上のため、圧縮してからアップロードすることをお勧めします。\n\nそれでも続けますか？',
    compressionError: '圧縮エラー:',
    failedToProcessImage: '画像の処理に失敗しました',
    processingImage: '処理中...',
    clickToUploadImage: 'クリックして画像をアップロード',
    maxFileSize: '最大 25MB',
    // Auth
    loginWelcomeBack: 'お帰りなさい',
    signInToContinue: '旅を続けるためにサインインしてください',
    emailLabel: 'メールアドレス',
    passwordLabel: 'パスワード',
    signInButton: 'サインイン',
    signingInButton: 'サインイン中...',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    signUpLink: 'サインアップ',
    backToHome: 'ホームに戻る',
    loginFailed: 'ログインに失敗しました',
    errorOccurred: 'エラーが発生しました。もう一度お試しください。',
    createAccount: 'アカウント作成',
    joinCommunitySubtitle: '今すぐBookVerseコミュニティに参加しましょう',
    usernameLabel: 'ユーザー名',
    usernamePlaceholder: 'unique_username',
    usernamePatternError: 'ユーザー名は文字、数字、ドット、アンダースコアのみ使用できます',
    usernameHelper: '文字、数字、ドット、アンダースコアのみ許可されています。',
    signUpButton: 'サインアップ',
    creatingAccountButton: 'アカウント作成中...',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    signInLink: 'サインイン',
    registrationFailed: '登録に失敗しました',
    // My Books Header
    myLibrary: 'マイライブラリ',
    manageMasterpieces: '傑作を管理しましょう。合計{{count}}のプロジェクトがあります。',
    projectsInTotal: 'プロジェクト合計',
    total: '合計',
    // BookList
    searchPlaceholder: 'ライブラリを検索...',
    allStatus: 'すべてのステータス',
    publishedStatus: '公開済み',
    draftStatus: '下書き',
    noBooksFound: '本が見つかりません',
    noBooksFoundDesc: '検索条件に一致する本が見つかりませんでした。フィルターを調整するか、新しい本を作成してください。',
    clearFilters: 'フィルターをクリア',
    noCover: '表紙なし',
    editBook: '本を編集',
    viewAnalytics: '分析を表示',
    startReadingParty: 'この本の読書パーティーを始めますか？',
    readingParty: '読書パーティー',
    deleteBookTitle: '本を削除',
    deleteConfirmation: '本当にこの本を削除しますか？この操作は取り消せません。',
    failedToDelete: '本の削除に失敗しました',
    failedToCreateRoom: 'ルームの作成に失敗しました',
    bookAnalytics: '書籍分析',
    // Analytics Dashboard
    failedToLoadAnalytics: '分析の読み込みに失敗しました',
    totalReaders: '総読者数',
    completionRate: '完了率',
    avgProgress: '平均進捗',
    readerRetention: '読者維持率（ファネル）',
    readersReachingEachPage: '各ページに到達した読者',
    pageLabel: 'ページ {{page}}',
    readersCount: '{{count}} 人の読者',
    // Communities
    connectCollaborate: 'つながり & コラボレーション',
    discoverTribe: 'あなたの部族を見つけよう',
    communitiesDesc: '議論に参加し、物語を共有し、あなたのために設計された専門コミュニティで仲間の読者や著者とつながりましょう。',
    createCommunity: 'コミュニティを作成',
    searchCommunities: 'コミュニティを検索...',
    bookVerseHub: 'BookVerse ハブ',
    officialCommunity: '公式コミュニティ',
    activeNow: '現在アクティブ',
    join: '参加',
    noCommunitiesFound: 'コミュニティが見つかりません',
    noCommunitiesDesc: 'まだコミュニティがないようです。最初のコミュニティを作成してパイオニアになりませんか？',
    createFirstCommunity: '最初のコミュニティを作成',
    allCommunities: 'すべてのコミュニティ',
    popular: '人気',
    newest: '最新',
    myCommunities: 'マイコミュニティ',
    fiction: 'フィクション',
    nonFiction: 'ノンフィクション',
    romance: 'ロマンス',
    sciFi: 'SF',
    defaultCommunityDesc: 'このコミュニティに参加して、他の人とつながり、情熱を共有しましょう。',
    member: 'メンバー',
    createCommunityTitle: 'コミュニティを作成',
    createCommunitySubtitle: '読者がお気に入りのトピックについて話し合うスペースを始めましょう。',
    communityName: 'コミュニティ名',
    communityNamePlaceholder: '例: ファンタジー愛好家',
    communityDescription: '説明',
    communityDescriptionPlaceholder: 'このコミュニティは何についてですか？',
    privacy: 'プライバシー',
    privacyOpen: '公開 (誰でも参加可能)',
    privacyClosed: '非公開 (承認が必要)',
    private: '非公開',
    community: 'コミュニティ',
    noDescription: '説明がありません。',
    requestPending: 'リクエスト保留中',
    requestToJoin: '参加リクエスト',
    joinCommunityButton: 'コミュニティに参加',
    communityFeed: 'コミュニティフィード',
    latest: '最新',
    top: 'トップ',
    quietInHere: '静かですね...',
    beTheFirst: 'このコミュニティで最初の会話を始めましょう！',
    aboutCommunity: 'コミュニティについて',
    aboutCommunityDesc: '私たちのコミュニティへようこそ！つながり、共有し、共に成長しましょう。',
    membersCount: 'メンバー',
    postsCount: '投稿',
    created: '作成日',
    createdBy: '作成者',
    failedToPost: '投稿に失敗しました',
    shareSomething: 'コミュニティと何か共有しましょう...',
    postButton: '投稿',
    like: 'いいね',
    likes: 'いいね',
    comments: 'コメント',
    writeComment: 'コメントを書く...',
    reply: '返信',
    loadMore: 'コメントをさらに読み込む',
    deleteCommunityConfirm: 'このコミュニティを削除してもよろしいですか？この操作は取り消せません。',
    failedToDeleteCommunity: 'コミュニティの削除に失敗しました',
    deleteCommunityButton: 'コミュニティを削除',
    noRecentActivity: '最近のアクティビティはありません',
    showLess: '表示を減らす',
    showMore: 'もっと見る',
    publishedBook: '公開しました',
    reviewedBook: '本をレビューしました',
    likedBook: '本にいいねしました',
    followedUser: 'フォローを開始しました',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['en', 'pt', 'jp'].includes(savedLang)) {
      // eslint-disable-next-line
      setLanguage((prev) => (prev !== savedLang ? savedLang : prev));
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let text = (translations[language] as any)[key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        // Support both {{key}} and {key} syntax
        text = text.replace(`{{${paramKey}}}`, String(value));
        text = text.replace(`{${paramKey}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
