'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'pt' | 'jp';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    overview: 'Overview',
    myBooks: 'My Books',
    communities: 'Communities',
    settings: 'Settings',
    createNewBook: 'Create New Book',
    signOut: 'Sign Out',
    bookVerse: 'BookVerse',
    browse: 'Browse',
    // Settings Page
    profileSettings: 'Profile Settings',
    visualIdentity: 'Visual Identity',
    profileAvatar: 'Profile Avatar',
    profileBanner: 'Profile Banner',
    languagePreferences: 'Language & Preferences',
    interfaceLanguage: 'Interface Language',
    languageHelp: 'Changes the language of the sidebar and menus.',
    personalInfo: 'Personal Info',
    username: 'Username',
    usernameHelp: 'Username cannot be changed',
    displayName: 'Display Name',
    bio: 'Bio',
    bioPlaceholder: 'Tell your story...',
    socialConnections: 'Social Connections',
    aiConfiguration: 'AI Configuration',
    geminiApiKey: 'Gemini API Key',
    apiKeyHelp: 'Your key is stored securely and used only for your requests.',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    livePreview: 'Live Preview',
    yourName: 'Your Name',
    bioPreview: 'Your biography will appear here...',
    // Create Book
    bookEditor: 'Book Editor',
    editingMode: 'Editing Mode',
    draftMode: 'Draft Mode',
    untitled: 'Untitled',
    chapter: 'Chapter',
    saveDraft: 'Save Draft',
    save: 'Save',
    publish: 'Publish',
    publishBook: 'Publish Book',
    aiAssistant: 'AI Assistant',
    apiKey: 'API Key',
    pasteApiKey: 'Paste your Gemini API Key...',
    generationMode: 'Generation Mode',
    completeBook: 'Complete Book',
    structureOnly: 'Structure Only',
    singlePage: 'Single Page',
    betaReader: 'Beta Reader',
    prompt: 'Prompt',
    describeScene: 'Describe the scene...',
    describeBook: 'Describe your book idea...',
    analysisResult: 'Analysis Result',
    analysisPlaceholder: 'Analysis results will appear here...',
    length: 'Length',
    pagesCount: 'Pages',
    short: 'Short',
    medium: 'Medium',
    long: 'Long',
    generate: 'Generate',
    generating: 'Thinking...',
    howToGetKey: 'How to get key?',
    tutorialTitle: 'Get your Gemini API Key',
    step1Title: 'Go to Google AI Studio',
    step1Desc: 'Visit the Google AI Studio to generate your free API key.',
    openStudio: 'Open Google AI Studio',
    step2Title: 'Create API Key',
    step2Desc: 'Click on "Create API key" and select a project (or create a new one).',
    step3Title: 'Copy & Paste',
    step3Desc: 'Copy the generated key starting with AIza... and paste it into the input field here.',
    gotIt: 'Got it',
    freeApiNote: '✨ The Gemini API is currently free to use for personal projects!',
    // Editor Sidebar
    pagesTab: 'Pages',
    settingsTab: 'Settings',
    teamTab: 'Team',
    aiTab: 'AI',
    charsTab: 'Chars',
    structure: 'Structure',
    pagesCountLabel: 'Pages',
    addNewPage: 'Add New Page',
    untitledPage: 'Untitled Page',
    pageIndex: 'Page',
    // Editor Settings
    coverImage: 'Cover Image',
    uploadCover: 'Upload Cover',
    // Overview Page
    welcomeBack: 'Welcome back, {name}!',
    premiumAuthorDashboard: 'Premium Author Dashboard',
    readyToCreate: 'Ready to create your next masterpiece? You have {books} books published and {communities} communities active.',
    writeNewBook: 'Write New Book',
    totalBooksPublished: 'Total Books Published',
    communitiesJoined: 'Communities Joined',
    active: 'Active',
    totalRevenue: 'Total Revenue',
    recentProjects: 'Recent Projects',
    viewAll: 'View All',
    noBooksCreated: 'No books created yet. Start your journey today!',
    published: 'PUBLISHED',
    draft: 'DRAFT',
    quickActions: 'Quick Actions',
    joinCommunity: 'Join Community',
    connectWithOthers: 'Connect with others',
    editProfile: 'Edit Profile',
    updateBio: 'Update your bio',
    wallet: 'Wallet',
    manageEarnings: 'Manage earnings',
    communityActivity: 'Community Activity',
    proTip: 'Pro Tip',
    proTipContent: 'Engaging with your community increases book sales by up to 40%.',
    goToCommunities: 'Go to Communities',
    description: 'Description',
    descriptionPlaceholder: 'Write a catchy blurb...',
    genres: 'Genres',
    addGenre: 'Add a Genre...',
    premiumContent: 'Premium Content',
    monetizeBook: 'Monetize your book',
    priceLabel: 'Price ($)',
    allowPdfDownload: 'Allow PDF Download',
    allowPdfDownloadDesc: 'Let readers download your book',
    ambience: 'Ambience',
    ambienceNone: 'None',
    ambienceRain: 'Rainy Day',
    ambienceFireplace: 'Cozy Fireplace',
    ambienceForest: 'Forest Sounds',
    ambienceCafe: 'Coffee Shop',
    ambienceSpace: 'Deep Space',
    ambienceOcean: 'Ocean Waves',
    // Editor Team
    inviteTeam: 'Invite Team',
    usernamePlaceholder: 'Username',
    saveBookFirst: 'Save the book first to add collaborators.',
    members: 'Members',
    activeMembers: 'Active',
    noCollaborators: 'No collaborators yet',
    // Editor Main
    autoSaving: 'Auto-saving',
    charsCount: 'chars',
    pageOf: 'Page',
    of: 'of',
    toggleFocusMode: 'Toggle Focus Mode',
    preview: 'Preview',
    edit: 'Edit',
    untitledBook: 'Untitled Book',
    currentChapter: 'Current Chapter',
    nothingWritten: 'Nothing written yet...',
    editorPlaceholder: 'Once upon a time...',
    // Rich Editor
    bold: 'Bold',
    italic: 'Italic',
    strikethrough: 'Strikethrough',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    bulletList: 'Bullet List',
    orderedList: 'Ordered List',
    quote: 'Quote',
    startWriting: 'Start writing...',
    // Image Upload
    uploadImage: 'Upload Image',
    uploading: 'Uploading...',
    imageUploadError: 'Error uploading image',
    imageUploadSuccess: 'Image uploaded successfully',
    selectImage: 'Select Image',
    changeImage: 'Change Image',
    removeImage: 'Remove Image',
    fileTooLarge: 'File is too large. Maximum size is 25MB.',
    largeImageWarning: 'This image is {{size}}MB.\n\nLarge images may take a long time to upload (30-60 seconds).\n\nConsider compressing it first for better performance.\n\nContinue anyway?',
    compressionError: 'Compression error:',
    failedToProcessImage: 'Failed to process image',
    processingImage: 'Processing...',
    clickToUploadImage: 'Click to upload image',
    maxFileSize: 'Max 25MB',
  },
  pt: {
    overview: 'Visão Geral',
    myBooks: 'Meus Livros',
    communities: 'Comunidades',
    settings: 'Configurações',
    createNewBook: 'Criar Novo Livro',
    signOut: 'Sair',
    bookVerse: 'BookVerse',
    browse: 'Explorar',
    // Settings Page
    profileSettings: 'Configurações de Perfil',
    visualIdentity: 'Identidade Visual',
    profileAvatar: 'Avatar do Perfil',
    profileBanner: 'Banner do Perfil',
    languagePreferences: 'Idioma e Preferências',
    interfaceLanguage: 'Idioma da Interface',
    languageHelp: 'Altera o idioma da barra lateral e menus.',
    personalInfo: 'Informações Pessoais',
    username: 'Nome de Usuário',
    usernameHelp: 'O nome de usuário não pode ser alterado',
    displayName: 'Nome de Exibição',
    bio: 'Biografia',
    bioPlaceholder: 'Conte sua história...',
    socialConnections: 'Conexões Sociais',
    aiConfiguration: 'Configuração de IA',
    geminiApiKey: 'Chave da API Gemini',
    apiKeyHelp: 'Sua chave é armazenada com segurança e usada apenas para suas solicitações.',
    saveChanges: 'Salvar Alterações',
    saving: 'Salvando...',
    livePreview: 'Pré-visualização',
    yourName: 'Seu Nome',
    bioPreview: 'Sua biografia aparecerá aqui...',
    // Create Book
    bookEditor: 'Editor de Livros',
    editingMode: 'Modo de Edição',
    draftMode: 'Modo Rascunho',
    untitled: 'Sem Título',
    chapter: 'Capítulo',
    saveDraft: 'Salvar Rascunho',
    save: 'Salvar',
    publish: 'Publicar',
    publishBook: 'Publicar Livro',
    aiAssistant: 'Assistente de IA',
    apiKey: 'Chave da API',
    pasteApiKey: 'Cole sua chave da API Gemini...',
    generationMode: 'Modo de Geração',
    completeBook: 'Livro Completo',
    structureOnly: 'Apenas Estrutura',
    singlePage: 'Página Única',
    betaReader: 'Leitor Beta',
    prompt: 'Prompt',
    describeScene: 'Descreva a cena...',
    describeBook: 'Descreva sua ideia de livro...',
    analysisResult: 'Resultado da Análise',
    analysisPlaceholder: 'Os resultados da análise aparecerão aqui...',
    length: 'Comprimento',
    pagesCount: 'Páginas',
    short: 'Curto',
    medium: 'Médio',
    long: 'Longo',
    generate: 'Gerar',
    generating: 'Pensando...',
    howToGetKey: 'Como obter a chave?',
    tutorialTitle: 'Obtenha sua chave da API Gemini',
    step1Title: 'Vá para o Google AI Studio',
    step1Desc: 'Visite o Google AI Studio para gerar sua chave de API gratuita.',
    openStudio: 'Abrir Google AI Studio',
    step2Title: 'Criar Chave de API',
    step2Desc: 'Clique em "Create API key" e selecione um projeto (ou crie um novo).',
    step3Title: 'Copiar e Colar',
    step3Desc: 'Copie a chave gerada começando com AIza... e cole-a no campo de entrada aqui.',
    gotIt: 'Entendi',
    freeApiNote: '✨ A API Gemini é atualmente gratuita para projetos pessoais!',
    // Editor Sidebar
    pagesTab: 'Páginas',
    settingsTab: 'Configurações',
    teamTab: 'Equipe',
    aiTab: 'IA',
    charsTab: 'Personagens',
    structure: 'Estrutura',
    monetizeBook: 'Monetize seu livro',
    priceLabel: 'Preço ($)',
    allowPdfDownload: 'Permitir Download de PDF',
    allowPdfDownloadDesc: 'Permitir que leitores baixem seu livro',
    ambience: 'Ambiente',
    ambienceNone: 'Nenhum',
    ambienceRain: 'Dia Chuvoso',
    ambienceFireplace: 'Lareira Aconchegante',
    ambienceForest: 'Sons da Floresta',
    ambienceCafe: 'Cafeteria',
    ambienceSpace: 'Espaço Profundo',
    ambienceOcean: 'Ondas do Oceano',
    // Editor Team
    inviteTeam: 'Convidar Equipe',
    usernamePlaceholder: 'Nome de usuário',
    saveBookFirst: 'Salve o livro primeiro para adicionar colaboradores.',
    members: 'Membros',
    activeMembers: 'Ativos',
    noCollaborators: 'Sem colaboradores ainda',
    // Editor Main
    autoSaving: 'Salvando auto.',
    charsCount: 'caracteres',
    pageOf: 'Página',
    of: 'de',
    toggleFocusMode: 'Alternar Modo Foco',
    preview: 'Visualizar',
    edit: 'Editar',
    untitledBook: 'Livro Sem Título',
    currentChapter: 'Capítulo Atual',
    nothingWritten: 'Nada escrito ainda...',
    editorPlaceholder: 'Era uma vez...',
    // Rich Editor
    bold: 'Negrito',
    italic: 'Itálico',
    strikethrough: 'Tachado',
    heading1: 'Título 1',
    heading2: 'Título 2',
    bulletList: 'Lista com Marcadores',
    orderedList: 'Lista Numerada',
    quote: 'Citação',
    startWriting: 'Comece a escrever...',
    // Image Upload
    uploadImage: 'Enviar Imagem',
    uploading: 'Enviando...',
    imageUploadError: 'Erro ao enviar imagem',
    imageUploadSuccess: 'Imagem enviada com sucesso',
    selectImage: 'Selecionar Imagem',
    changeImage: 'Alterar Imagem',
    removeImage: 'Remover Imagem',
    fileTooLarge: 'O arquivo é muito grande. O tamanho máximo é 25MB.',
    largeImageWarning: 'Esta imagem tem {{size}}MB.\n\nImagens grandes podem demorar para carregar (30-60 segundos).\n\nConsidere comprimi-la primeiro para melhor desempenho.\n\nContinuar mesmo assim?',
    compressionError: 'Erro de compressão:',
    failedToProcessImage: 'Falha ao processar imagem',
    processingImage: 'Processando...',
    clickToUploadImage: 'Clique para enviar imagem',
    maxFileSize: 'Máx 25MB',
  },
  jp: {
    overview: '概要',
    myBooks: '私の本',
    communities: 'コミュニティ',
    settings: '設定',
    createNewBook: '新しい本を作成',
    signOut: 'サインアウト',
    bookVerse: 'ブックバース',
    browse: '閲覧',
    // Settings Page
    profileSettings: 'プロフィール設定',
    visualIdentity: 'ビジュアルアイデンティティ',
    profileAvatar: 'プロフィールアバター',
    profileBanner: 'プロフィールバナー',
    languagePreferences: '言語と設定',
    interfaceLanguage: 'インターフェース言語',
    languageHelp: 'サイドバーとメニューの言語を変更します。',
    personalInfo: '個人情報',
    username: 'ユーザー名',
    usernameHelp: 'ユーザー名は変更できません',
    displayName: '表示名',
    bio: '自己紹介',
    bioPlaceholder: 'あなたの物語を語ってください...',
    socialConnections: 'ソーシャル接続',
    aiConfiguration: 'AI設定',
    geminiApiKey: 'Gemini APIキー',
    apiKeyHelp: 'キーは安全に保存され、リクエストにのみ使用されます。',
    saveChanges: '変更を保存',
    saving: '保存中...',
    livePreview: 'ライブプレビュー',
    yourName: 'あなたの名前',
    bioPreview: 'あなたの自己紹介がここに表示されます...',
    // Create Book
    bookEditor: 'ブックエディター',
    editingMode: '編集モード',
    draftMode: '下書きモード',
    untitled: '無題',
    chapter: '章',
    saveDraft: '下書きを保存',
    save: '保存',
    publish: '公開',
    publishBook: '本を出版',
    aiAssistant: 'AIアシスタント',
    apiKey: 'APIキー',
    pasteApiKey: 'Gemini APIキーを貼り付けてください...',
    generationMode: '生成モード',
    completeBook: '本全体',
    structureOnly: '構成のみ',
    singlePage: '単一ページ',
    betaReader: 'ベータリーダー',
    prompt: 'プロンプト',
    describeScene: 'シーンを説明してください...',
    describeBook: '本のアイデアを説明してください...',
    analysisResult: '分析結果',
    analysisPlaceholder: '分析結果がここに表示されます...',
    length: '長さ',
    pagesCount: 'ページ数',
    short: '短い',
    medium: '中くらい',
    long: '長い',
    generate: '生成',
    generating: '考え中...',
    howToGetKey: 'キーの取得方法',
    tutorialTitle: 'Gemini APIキーを取得する',
    step1Title: 'Google AI Studioへ移動',
    step1Desc: 'Google AI Studioにアクセスして、無料のAPIキーを生成します。',
    openStudio: 'Google AI Studioを開く',
    step2Title: 'APIキーを作成',
    step2Desc: '「Create API key」をクリックし、プロジェクトを選択（または新規作成）します。',
    step3Title: 'コピー＆ペースト',
    step3Desc: 'AIza...で始まる生成されたキーをコピーして、ここの入力フィールドに貼り付けます。',
    gotIt: '了解',
    freeApiNote: '✨ Gemini APIは現在、個人プロジェクトで無料で使用できます！',
    // Editor Sidebar
    pagesTab: 'ページ',
    settingsTab: '設定',
    teamTab: 'チーム',
    aiTab: 'AI',
    charsTab: 'キャラ',
    structure: '構成',
    pagesCountLabel: 'ページ',
    addNewPage: '新しいページを追加',
    untitledPage: '無題のページ',
    pageIndex: 'ページ',
    // Editor Settings
    coverImage: '表紙画像',
    uploadCover: '表紙をアップロード',
    // Overview Page
    welcomeBack: 'お帰りなさい、{name}さん！',
    premiumAuthorDashboard: 'プレミアム著者ダッシュボード',
    readyToCreate: '次の傑作を作る準備はできましたか？ {books}冊の本が出版され、{communities}つのコミュニティがアクティブです。',
    writeNewBook: '新しい本を書く',
    totalBooksPublished: '出版された本の総数',
    communitiesJoined: '参加しているコミュニティ',
    active: 'アクティブ',
    totalRevenue: '総収益',
    recentProjects: '最近のプロジェクト',
    viewAll: 'すべて見る',
    noBooksCreated: 'まだ本が作成されていません。今日から旅を始めましょう！',
    published: '公開済み',
    draft: '下書き',
    quickActions: 'クイックアクション',
    joinCommunity: 'コミュニティに参加',
    connectWithOthers: '他の人とつながる',
    editProfile: 'プロフィールを編集',
    updateBio: '自己紹介を更新',
    wallet: 'ウォレット',
    manageEarnings: '収益を管理',
    communityActivity: 'コミュニティ活動',
    proTip: 'プロのヒント',
    proTipContent: 'コミュニティと交流することで、本の売り上げが最大40％増加します。',
    goToCommunities: 'コミュニティへ移動',
    description: '説明',
    descriptionPlaceholder: '魅力的な宣伝文句を書いてください...',
    genres: 'ジャンル',
    addGenre: 'ジャンルを追加...',
    premiumContent: 'プレミアムコンテンツ',
    monetizeBook: '本を収益化',
    priceLabel: '価格 ($)',
    allowPdfDownload: 'PDFダウンロードを許可',
    allowPdfDownloadDesc: '読者が本をダウンロードできるようにする',
    ambience: '環境音',
    ambienceNone: 'なし',
    ambienceRain: '雨の日',
    ambienceFireplace: '居心地の良い暖炉',
    ambienceForest: '森の音',
    ambienceCafe: 'コーヒーショップ',
    ambienceSpace: '深宇宙',
    ambienceOcean: '海の波',
    // Editor Team
    inviteTeam: 'チームを招待',
    usernamePlaceholder: 'ユーザー名',
    saveBookFirst: 'コラボレーターを追加するには、まず本を保存してください。',
    members: 'メンバー',
    activeMembers: 'アクティブ',
    noCollaborators: 'コラボレーターはまだいません',
    // Editor Main
    autoSaving: '自動保存中',
    charsCount: '文字',
    pageOf: 'ページ',
    of: '/',
    toggleFocusMode: 'フォーカスモード切替',
    preview: 'プレビュー',
    edit: '編集',
    untitledBook: '無題の本',
    currentChapter: '現在の章',
    nothingWritten: 'まだ何も書かれていません...',
    editorPlaceholder: '昔々あるところに...',
    // Rich Editor
    bold: '太字',
    italic: '斜体',
    strikethrough: '取り消し線',
    heading1: '見出し 1',
    heading2: '見出し 2',
    bulletList: '箇条書き',
    orderedList: '番号付きリスト',
    quote: '引用',
    startWriting: '書き始める...',
    // Image Upload
    uploadImage: '画像をアップロード',
    uploading: 'アップロード中...',
    imageUploadError: '画像のアップロードエラー',
    imageUploadSuccess: '画像が正常にアップロードされました',
    selectImage: '画像を選択',
    changeImage: '画像を変更',
    removeImage: '画像を削除',
    fileTooLarge: 'ファイルが大きすぎます。最大サイズは25MBです。',
    largeImageWarning: 'この画像は{{size}}MBです。\n\n大きな画像はアップロードに時間がかかる場合があります（30〜60秒）。\n\nパフォーマンス向上のため、圧縮してからアップロードすることをお勧めします。\n\nそれでも続けますか？',
    compressionError: '圧縮エラー:',
    failedToProcessImage: '画像の処理に失敗しました',
    processingImage: '処理中...',
    clickToUploadImage: 'クリックして画像をアップロード',
    maxFileSize: '最大 25MB',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['en', 'pt', 'jp'].includes(savedLang)) {
      // eslint-disable-next-line
      setLanguage((prev) => (prev !== savedLang ? savedLang : prev));
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let text = (translations[language] as any)[key] || key;
    
    if (params) {
      Object.entries(params).forEach(([key, value]) => {
        text = text.replace(`{{${key}}}`, String(value));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
